### PR TITLE
use builtin M_PI

### PR DESCRIPTION
**Pull request by mzhaodev**

### CODE REVIEW

**Comment by ImpregnableProgrammer** [comment]
@thepiercingarrow  Why should I use the builtin M_PI? Aren't both the PI I defined and builtin M_PI pretty much the same thing?

**Comment by mzhaodev** [comment]
M_PI is (usually) defined to double precision. From my `/usr/include/math.h`, I see the line:

```
#define M_PI        3.14159265358979323846264338327950288   /* pi             */
```

which is a few digits more accurate than your definition.
Also I think its better practice and more well-known to use the `M_PI` constant.

**Comment by ImpregnableProgrammer** [comment]
@thepiercingarrow Well, I just wanted to make it so that I have to use as few builtins from the `math.h` header file as possible to make it so that the header file is not really needed and the user can get rid of it unless he/she wants to compare the built-in trigonometric functions to my own. Plus, I can make by own even more accurate representation of `pi` if I want to, which I am going to do right now.

**Comment by mzhaodev** [comment]
Yes, that is why I added the guard:

```
#ifndef M_PI
#define M_PI 3.14159265358979323846263279
#endif
```

so that your code will automatically define `M_PI` if it is undefined (for e.g. `math.h` is not included).

**Comment by ImpregnableProgrammer** [comment]
@thepiercingarrow Okay, I will merge your request with a little bit of changes from me.

**Comment by ImpregnableProgrammer** [comment]
@thepiercingarrow Done. By the way, what do you think of the rest of my code?

**Comment by thepiercingarrow** [comment]
Your code is pretty well organized and readable. However, there are a few small problems, for example your factorial function, which doesn't work for inputs 0 and 1. An easier way (which might be a bit slower, idk) is to just have:
```
int factorial(int x) {
    return x < 2 ? 1 : x  * factorial(x - 1);
}
```
but that's code golfed lol.
Or you can just start your index at `i = 0` rather than `i = 2`.

**Comment by ImpregnableProgrammer** [comment]
@thepiercingarrow But it does work for inputs `0` and `1`. `0!` and `1!` are both `1`, correct? That is what my function outputs when executed with those inputs. [Check it out](http://ideone.com/Bfs9Df). Also, what you proposed is recursive, which would make my `factorial` function much slower than it already is. I really don't want that, especially for what I'm trying to do.

**Comment by mzhaodev** [comment]
Gaa I am stupid. Sorry (deleted comment).

**Comment by ImpregnableProgrammer** [comment]
@thepiercingarrow Okay. Anything else?

**Pull request merged**
